### ISSUE TITLE
评论显示错误

### ISSUE THREAD

**Issue by Cloud33** [xiaoyaocz/flutter_cnblogs#1]
点击评论显示加载错误。
![dcc3e84efa5da09058a6601f44d9cee](https://user-images.githubusercontent.com/8787198/208065338-0f8569ce-e42d-4375-8a3a-875fd8504fa3.jpg)

我应该是点击48小时排行榜的文章，所以应该是22以后的评论

**Comment by xiaoyaocz** [comment]
请提供一下具体文章链接

**Comment by Cloud33** [comment]
https://www.cnblogs.com/coco1s/p/16983408.html

好像原因是需要登录能才看到评论？
