### ISSUE TITLE
我的博客里文章点赞都为0

### ISSUE THREAD

**Issue by KoiC-UP** [xiaoyaocz/flutter_cnblogs#2]
![Screenshot_2023-02-14-23-12-01-06_a9f68f451cc80254bc8c3ccd58548cb9](https://user-images.githubusercontent.com/65055620/218778564-c743f4f8-b1c7-4fbf-a3ce-787fae6e34a0.jpg)

像第一篇文章是有两个点赞的，现在全部都显示为0

**Comment by xiaoyaocz** [comment]
应该是博客园接口的问题，返回的DiggCount字段都是0
https://api.cnblogs.com/api/blogs/{blogApp}/posts?pageIndex={pageIndex}

**Comment by KoiC-UP** [comment]
明白了，感谢您的回复
